export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';
export const CLEAR_TODO_LIST = 'CLEAR_TODO_LIST';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const GET_TODO_LIST = 'GET_TODO_LIST';
export const LOAD_SAVED_TODO_LIST = 'LOAD_SAVED_TODO_LIST';